// The image entrypoint that brings a sandbox up with its runtime already
// ready. Kept apart from runtime-environment.ts because it also needs the
// client module's pairing command, and that module imports runtime-environment.

import type { SandboxRuntimeLayout } from "../sandboxes/provider";
import { buildRuntimeEnvironmentAuthenticationCommand, RUNTIME_COOKIE_JAR } from "./runtime-environment-client";
import {
  buildRuntimeEnvironmentLaunchCommand,
  buildRuntimeEnvironmentReadinessCommand,
  ROOT_RUNTIME_LAYOUT,
  RUNTIME_BOOT_MARKER,
  RUNTIME_ENVIRONMENT_PORT,
} from "./runtime-environment";

/** Where the native image installs the boot entrypoint. */
export function runtimeEnvironmentBootPath(layout: SandboxRuntimeLayout = ROOT_RUNTIME_LAYOUT): string {
  return `${layout.home}/.local/bin/useagent-sandbox-boot`;
}

/**
 * The image's entrypoint. A fresh sandbox used to come up idle and the plane
 * started the runtime, polled it ready, paired a session and made the first
 * shell request on the run's critical path, close to thirty seconds. This
 * script does all of that while the sandbox boots: the runtime starts with the
 * flags the plane baked, readiness is the plane's own probe, the pairing leaves
 * the plane's cookie jar in place, and one shell request builds the runtime's
 * state. The plane then finds a ready runtime and moves straight on. The
 * runtime is a background child; the script keeps the container alive
 * separately, so a plane-driven restart (pkill, relaunch) leaves the container
 * up. A marker file shows the plane a boot in progress so it waits instead of
 * restarting. Every step is best effort: a failure here leaves the sandbox idle
 * and the plane repairs it as before.
 */
export function buildRuntimeEnvironmentBootScript(
  env: Readonly<Record<string, string | undefined>> = process.env,
  layout: SandboxRuntimeLayout = ROOT_RUNTIME_LAYOUT,
): string {
  const runtimeHome = `${layout.home}/.skynet/t3`;
  const shell = (script: string) => `sh -c ${quoteShell(script)}`;
  return [
    "#!/bin/sh",
    "# useagent-sandbox-boot: generated by backend/src/engines/runtime-environment-boot.ts; do not edit.",
    `export HOME="${layout.home}"`,
    `mkdir -p "${runtimeHome}"`,
    // The plane waits on this marker instead of restarting a runtime that is still coming up.
    `touch "${RUNTIME_BOOT_MARKER}"`,
    `nohup ${shell(buildRuntimeEnvironmentLaunchCommand(env, layout))} >"${runtimeHome}/boot.log" 2>&1 &`,
    "i=0",
    `until ${shell(buildRuntimeEnvironmentReadinessCommand(env))}; do`,
    '  i=$((i + 1)); [ "$i" -ge 600 ] && break',
    "  sleep 0.1",
    "done",
    `rm -f "${RUNTIME_BOOT_MARKER}"`,
    `${shell(buildRuntimeEnvironmentAuthenticationCommand(layout))} >>"${runtimeHome}/boot.log" 2>&1 || true`,
    `curl -sS -m 60 -b "${RUNTIME_COOKIE_JAR}" -H 'accept: application/json' -o /dev/null http://127.0.0.1:${RUNTIME_ENVIRONMENT_PORT}/api/orchestration/shell || true`,
    // A launcher that hands the image a command (a provider daemon, the runner's own idle command) gets it run.
    '[ "$#" -gt 0 ] && exec "$@"',
    "exec sleep infinity",
    "",
  ].join("\n");
}

function quoteShell(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}
